---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon EKS Fargate Pod Execution Role'


Resources:

  eksFargatePodExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks-fargate-pods.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy

Outputs:

  RoleArn:
    Description: The role that Amazon EKS will use to create pods in Fargate infrastructure
    Value: !GetAtt eksFargatePodExecutionRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-RoleArn"